### ISSUE TITLE
Expanding on the sample example in the documentation

### ISSUE THREAD

**Issue by abhimaniyar** [amoradinejad/limHaloPT#12] opened 2022-03-15 23:35 UTC
Following up on the previous issue (#10), I would urge you to add more details in the documentation on the sample run/runs to check the performance of the code. This should give an idea to the user how to use the code and what output/outputs should be expected.

**Comment by ziotom78** [comment] 2022-03-24 17:35
I believe this is a duplicate of #11

**Comment by amoradinejad** [comment] 2022-04-06 15:05
Please see the response to #12.

**Closed** 2022-04-06 23:14 UTC
